"""

Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
# A function which outputs a list of fibbonacci numbers less than N
def fib(N):
    prev, prev2 = 1,0
    fibList = [prev2, prev]
    while prev + prev2 < N:
        prev, prev2 = prev + prev2, prev
        fibList.append(prev)

    return fibList

def isEven(x):
    return not(x % 2)



# Build a list of fibonacci numbers:
fibList = fib(4000000)

# Filter out odd nums
filtered = filter(isEven, fibList)

# Find the sum
print(sum(filtered))
